name: rust-build

on:
  pull_request:
    branches:
      - '**'
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-repo:
    name: Build repository
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
